version: '3.7'

services:
  kong:
    image: kong:latest
    container_name: kong-dbless
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong-config/kong.yml
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    volumes:
      - ./kong.yml:/kong-config/kong.yml:ro
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
